# Categories Array - (Genres) - https://www.novelupdates.com/genre-explanation/
GENRES = [
    "action",
    "adult",
    "adventure",
    "comedy",
    "drama",
    "ecchi",
    "fantasy",
    "gender bender",
    "harem",
    "historical",
    "horror",
    "josei",
    "martial arts",
    "mature",
    "mecha",
    "mystery",
    "psychological",
    "romance",
    "school life",
    "sci-fi",
    "seinen",
    "shoujo",
    "shoujo ai",
    "shounen",
    "shounen ai",
    "slice of life",
    "smut",
    "sports",
    "supernatural",
    "tragedy",
    "wuxia",
    "xianxia",
    "xuanhuan",
    "yaoi",
    "yuri",
]