from pathlib import Path
from types import SimpleNamespace

import typer
from typing_extensions import Annotated
from stalkers_cli.core.format_all import book_all
from stalkers_cli.core.metadata.sources.good_reads import GoodReadsSource
from stalkers_cli.core.scripts import extract_chapters, format_book
from utils import OUTPUT_FOLDER_NAME, open_in_file_explorer

app = typer.Typer(no_args_is_help=True, add_completion=False)

OPTIONS_HELP_TEXT = {
    "root" : "Root folder generated by the lightnovel-crawler script",
    "stopClass": "Classname of the stop container",
    "stopTag": "HTML Tag of the stop container",
    "author": "Book's author",
    "title": "Book's title",
    "uri": "Uri for the goodreads.com book page"
}

@app.callback()
def main(
    ctx: typer.Context,
    root: Annotated[Path, typer.Option('--root','-r', help=OPTIONS_HELP_TEXT["root"], prompt="Root Folder", exists=True)] = None,
):
    if not root:
        print("Missing root folder. Pass --root / -r")
        raise typer.Exit(1)
    
    # create output folder (root/formatted-novel)
    output_folder = Path(f"{root}/{OUTPUT_FOLDER_NAME}")
    output_folder.mkdir(parents=True, exist_ok=True)

    ctx.obj = SimpleNamespace(root = root, output_folder=output_folder)


@app.command('all', help="format and extract")
def all(
    ctx: typer.Context,
    stopTag: Annotated[str, typer.Option('--stop-tag', "-st" , help=OPTIONS_HELP_TEXT["stopTag"], prompt=True)] = None,
    stopClass: Annotated[str, typer.Option('--stop-class', "-sc" , help=OPTIONS_HELP_TEXT["stopClass"], prompt=True)] = None,
    containerClass: Annotated[str, typer.Option('--container-class', "-cc" , help=OPTIONS_HELP_TEXT["stopClass"])] = "block",
    uri: Annotated[str, typer.Option('--uri', '-u',help=OPTIONS_HELP_TEXT["uri"], prompt="URI")] = None
):
    stop = {"tag": stopTag, "className": stopClass}

    format_book(root=ctx.obj.root, stop=stop)
    extract_chapters(output=ctx.obj.output_folder, container_className=containerClass)
    source = GoodReadsSource(novel_uri=uri, output_folder=ctx.obj.output_folder)
    source.extract_metadata()
    
    book_all(output_folder=ctx.obj.output_folder)

    open_in_file_explorer(ctx.obj.root)


@app.command('fhtml', help="Format the html of a book")
def format(
    ctx: typer.Context,
    stopTag: Annotated[str, typer.Option('--stop-tag', "-st" , help=OPTIONS_HELP_TEXT["stopTag"], prompt=True)] = None,
    stopClass: Annotated[str, typer.Option('--stop-class', "-sc" , help=OPTIONS_HELP_TEXT["stopClass"], prompt=True)] = None,
):
    stop = {"tag": stopTag, "className": stopClass}
    format_book(root=ctx.obj.root, stop=stop)

    open_in_file_explorer(ctx.obj.root)


@app.command('extract', help="extract chapters from a book")
def extract_chapters_from_html(
    ctx: typer.Context,
    containerClass: Annotated[str, typer.Option('--container-class', "-cc" , help=OPTIONS_HELP_TEXT["stopClass"])] = "block",
):
    extract_chapters(output=ctx.obj.output_folder, container_className=containerClass)


@app.command("metadata", help="extract book's metadata from goodreads.com")
def metadata(
    ctx: typer.Context,
    uri: Annotated[str, typer.Option('--uri', '-u',help=OPTIONS_HELP_TEXT["uri"], prompt="URI")] = None
):
    source = GoodReadsSource(novel_uri=uri, output_folder=ctx.obj.output_folder)
    source.extract_metadata()